version: '3.8'

services:
  geof232:
    build: .
    platform: linux/arm64
    container_name: geof232-fjordoceanography
    volumes:
      - /Users/klaraeelise/Projects/uni/fjordoceanography:/workspace
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    working_dir: /workspace